name: branch-watcher  
run-name: ${{ github.actor }} is just pushed a commit
on: 
  push:
    branches:
      - main
jobs:
  branch-watcher:
    runs-on: ubuntu-latest
    steps:
      - run: checkout project-a
      - run: merge main
