name: branch-watcher  
run-name: ${{ github.actor }} is just pushed a commit
on: 
  push:
    branches:
      - main
jobs:
  branch-watcher:
    runs-on: ubuntu-latest
    steps:
      - run: git init
      - run: git config --global init.defaultBranch main
      - run: git checkout remotes/origin/project-a
      - run: git merge remotes/origin/main
